# Jekyll config file
remote_theme: pages-themes/slate@v0.2.0
show_downloads: true
plugins:
- jekyll-remote-theme

download:
  encoder_url: https://github.com/mdoryammilwalrus/scratchattach-node/raw/main/assets/Encoder.sprite3
  cloud_requests_template_url: https://github.com/mdoryammilwalrus/scratchattach-node/raw/main/assets/CloudRequests_Template.sb3
